### ISSUE TITLE
处理上报的路由在哪里配置

### ISSUE THREAD

**Issue by chengqilong** [LianjiaTech/fee#1]
server下,处理上报的路由的地址在哪里配置(比如:https://dig.xxxx.com/fee.gif?d=)

**Comment by YaoZeyuan** [comment]
打点记录由Ngnix承接
Ngnix将请求记录到日志后再通过SaveLog:Nginx命令从日志中解析数据, 进行处理
可以参考[parseNginxLog.js](https://github.com/LianjiaTech/fee/blob/master/server/src/commands/save_log/parseNginxLog.js)这个文件的内容
