### ISSUE TITLE
Commands:parseNginxLog自动清理旧Stream有问题

### ISSUE THREAD

**Issue by JeasonSun** [LianjiaTech/fee#12]
**parseNginxLog里面由于在分析83行，定期清理stream：**
jsonWriteStreamPool.size > 100 || rawLogWriteStreamPool.size > 100 ，由于jsonWriteStreamPool和rawLogWriteStreamPool都是NginxParseLog子类中定义的Map，没有对相关map进行set处理，所以，size应该永远是0，这个判断应该去base中获取jsonWriteStreamPool的size。

**在save_log/base中，63行，autoCloseOldStream循环：**
首先是10分钟之内，startAt = nowAt - 60 * 100，finishAt = nowAt - 60 * 100，那不是startAt===finishAt了么？ 其次，循环中 let survivalAtLogUri = LKafka.getAbsoluteLogUriByType(nowAt, LKafka.LOG_TYPE_JSON)  使用nowAt去获取文件路径，按照目前的逻辑，只有nowAt这一刻的stream可以幸免被关闭。原本设计的应该是获取10分钟内需要被避免关闭的stream，然后关闭其他。所以这边应该是LKafka.getAbsoluteLogUriByType(survivalAt, LKafka.LOG_TYPE_JSON)

**Comment by alphawq** [comment]
感谢反馈！

> **parseNginxLog里面由于在分析83行，定期清理stream：**

_**Bug fixed**_

> **在save_log/base中，63行，autoCloseOldStream循环：**

_**Bug fixed**_
