### ISSUE TITLE
/api/user/register

### ISSUE THREAD

**Issue by JeasonSun** [LianjiaTech/fee#16]
server/src/routes/api/user/index.js 中 /api/user/register 路由：
129行，判断此账号是否存在，let rawUser = MUser.getByAccount(account)，应该加await，不然直接走“账号已存在”

**Comment by alphawq** [comment]
> server/src/routes/api/user/index.js 中 /api/user/register 路由：
> 129行，判断此账号是否存在，let rawUser = MUser.getByAccount(account)，应该加await，不然直接走“账号已存在”

**_Bug fixed!_**
