### ISSUE TITLE
有个问题

### ISSUE THREAD

**Issue by htoooth** [LianjiaTech/fee#2]
```js
window.addEventListener('error', function(e) {
console.log(e);
}, true)
```

会调用两次，也就是说会打印两次错误，这是为什么呢

**Comment by YaoZeyuan** [comment]
![image](https://user-images.githubusercontent.com/7150325/56482021-7b9a0500-64f4-11e9-8de5-cde571c9a47a.png)
因为你的测试页面里真的有两处错误:joy:
