### ISSUE TITLE
项目启动报错

### ISSUE THREAD

**Issue by bailuo** [LianjiaTech/fee#4]
按照文档指引，启动项目后，在clinet端会报找不到文件的错误，然后去查看了一下view下确实缺少device-detail/mobileview.vue。将这部分相关的代码注释掉后项目成功启动

**Comment by Elena222** [comment]
请问你注册成功了吗？ 我注册时候服务器500。。

**Comment by chasel** [comment]
我也遇到同样的问题，直接注释掉页面中相关的代码解决的
